Merge Routing Pages Into Main
mckinleyevans-wrdsb/Panther-Pals pull request #53
Opened 2023-05-19 16:20 UTC by Qurea2166

2023-05-19 17:32 UTC, mckinleyevans-wrdsb requested changes, later dismissed

2023-05-19 17:32 UTC, mckinleyevans-wrdsb commented on announcements/index.html
> +  <script src="../script.js"></script>
Remove this line

2023-05-19 17:32 UTC, mckinleyevans-wrdsb commented on calendar/index.html
> +  <script src="../script.js"></script>
Remove this line

2023-05-19 17:32 UTC, mckinleyevans-wrdsb commented on index.html
> +  <script src="./script.js"></script>
Remove this line

2023-05-23 16:09 UTC, Harman0909 approved these changes

2023-05-23 16:09 UTC, merged